:doctype: book
:toc: left
:toclevels: 4

= Progetto

== Progetto Vaadin
1. Creare una nuova app -> https://start.vaadin.com/app
2. Scaricare e unzippare nella directory -> /Users/gac/Documents/IdeaProjects/operativi
3. Aprirlo da IntelliJ IDEA
4. Controllare che File -> Project structure -> Project -> SDK sia selezionato su '17 version 17'. Se manca, crearlo -> **New**
5. Controllare che File -> Project structure -> Project -> Language level sia selezionato su LTS Version -> 17 - Sealed types
6. Eseguire (opzionale) da terminale interno -> ./mvnw
7. Eseguire (meglio) Maven (bordo destro) -> Lifecycle -> clean && install (insieme con melaClick)
8. Per lancio normale aprire Run/Debug Configurations -> + Add New Configurations -> Spring Boot
9. Cliccare su Build and run -> Modify options -> Spring Boot e confermare la **main class** col nome dell'applicazione
10. Cambiare name **Unnamed** -> Nome dell'applicazione e cliccare su **OK**
11. Aprire il file **pom.xml** e modificare **<version>1.0-SNAPSHOT</version>** in **<version>1.0</version>**


== Git

=== Ignore

- Controllare che esista il file (nascosto) **.gitignore**
- Se manca recuperarlo

=== Aggiunti da Alkgos
- build/
- out/
- log/


== GitHub

- Aprire VCS -> Import into Version Control -> Share Project on GitHub...
- Confermare -> **Share**

== POM

== Vaadin

- Replace artifactId with vaadin-core to use only free components
- Aggiungere <exclusions>: Webjars are only needed when running in Vaadin 13 compatibility mode

== Dependency

- Spring MongoDB
- Lombok

== Install

- On terminal run: **npm install**
- Aggiungere (obbligatorio) resources -> application.properties
- Aggiungere (facoltativo) resources -> banner.txt